export const PERMISSIONS = {
  USERS_VIEW: "users:view",
  USERS_CREATE: "users:create",
  USERS_EDIT: "users:edit",
  USERS_APPROVE: "users:approve",
  USERS_CANCEL: "users:cancel",
  USERS_EXPORT: "users:export",
  ROLES_VIEW: "roles:view",
  ROLES_MANAGE: "roles:manage",
  BRANCHES_VIEW: "branches:view",
  BRANCHES_CREATE: "branches:create",
  BRANCHES_EDIT: "branches:edit",
  BRANCHES_APPROVE: "branches:approve",
  BRANCHES_MANAGE: "branches:manage",
  SETTINGS_VIEW: "settings:view",
  SETTINGS_EDIT: "settings:edit",
  SETTINGS_MANAGE: "settings:manage",
  AUDIT_VIEW: "audit:view",
  AUDIT_EXPORT: "audit:export",
  MASTERS_VIEW: "masters:view",
  MASTERS_CREATE: "masters:create",
  MASTERS_EDIT: "masters:edit",
  MASTERS_CANCEL: "masters:cancel",
  MASTERS_EXPORT: "masters:export",
  PRODUCTS_VIEW: "products:view",
  PRODUCTS_CREATE: "products:create",
  PRODUCTS_EDIT: "products:edit",
  PRODUCTS_CANCEL: "products:cancel",
  PRODUCTS_EXPORT: "products:export",
  ACCOUNTS_VIEW: "accounts:view",
  ACCOUNTS_MANAGE: "accounts:manage",
  PURCHASES_VIEW: "purchases:view",
  PURCHASES_CREATE: "purchases:create",
  PURCHASES_EDIT: "purchases:edit",
  PURCHASES_CANCEL: "purchases:cancel",
  PURCHASES_EXPORT: "purchases:export",
  SALES_VIEW: "sales:view",
  SALES_CREATE: "sales:create",
  SALES_EDIT: "sales:edit",
  SALES_CANCEL: "sales:cancel",
  SALES_EXPORT: "sales:export",
  SALES_APPROVE: "sales:approve",
  OLDGOLD_VIEW: "oldgold:view",
  OLDGOLD_CREATE: "oldgold:create",
  OLDGOLD_EDIT: "oldgold:edit",
  OLDGOLD_CANCEL: "oldgold:cancel",
  OLDGOLD_EXPORT: "oldgold:export",
  OLDGOLD_APPROVE: "oldgold:approve",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export function hasPermission(granted: string[], required: string): boolean {
  return granted.includes(required);
}

const ALL = Object.values(PERMISSIONS);

export const DEFAULT_ROLES: Record<string, string[]> = {
  owner: [...ALL],
  manager: ALL.filter((p) => p !== "users:approve" && p !== "branches:approve"),
  accountant: [
    "users:view",
    "roles:view",
    "branches:view",
    "settings:view",
    "audit:view",
    "audit:export",
    "masters:view",
    "masters:export",
    "products:view",
    "products:export",
    "accounts:manage",
    "purchases:view",
    "purchases:export",
    "sales:view",
    "sales:export",
    "oldgold:view",
    "oldgold:export",
  ],
  cashier: ["users:view", "branches:view", "masters:view", "products:view", "accounts:view", "purchases:view", "sales:view", "sales:create", "oldgold:view", "oldgold:create"],
  salesperson: ["branches:view", "masters:view", "products:view", "purchases:view", "sales:view", "sales:create", "oldgold:view"],
  inventory_officer: [
    "branches:view",
    "masters:view",
    "masters:create",
    "masters:edit",
    "masters:cancel",
    "masters:export",
    "products:view",
    "products:create",
    "products:edit",
    "products:cancel",
    "products:export",
    "purchases:view",
    "purchases:create",
    "purchases:edit",
    "sales:view",
    "oldgold:view",
  ],
  gold_officer: [
    "branches:view",
    "masters:view",
    "masters:create",
    "masters:export",
    "products:view",
    "purchases:view",
    "sales:view",
    "oldgold:view",
    "oldgold:create",
    "oldgold:edit",
  ],
  manufacturing_staff: ["products:view"],
};
