import { Hono } from "hono";
import type { Env } from "./db/client";
import { errorHandler } from "./middleware/error";
import { cors } from "./middleware/cors";
import { accounts } from "./routes/accounts";
import { audit } from "./routes/audit";
import { auth } from "./routes/auth";
import { branches } from "./routes/branches";
import { catalog } from "./routes/catalog";
import { health } from "./routes/health";
import { customers, suppliers } from "./routes/parties";
import { inventory } from "./routes/inventory";
import { products } from "./routes/products";
import { purchases } from "./routes/purchases";
import { rates } from "./routes/rates";
import { roles } from "./routes/roles";
import { settings } from "./routes/settings";
import { users } from "./routes/users";

const app = new Hono<{ Bindings: Env }>();
app.onError(errorHandler);
app.use("/api/*", cors);
app.route("/api/v1/health", health);
app.route("/api/v1/auth", auth);
app.route("/api/v1/users", users);
app.route("/api/v1/roles", roles);
app.route("/api/v1/branches", branches);
app.route("/api/v1/settings", settings);
app.route("/api/v1/audit", audit);
app.route("/api/v1/masters", catalog);
app.route("/api/v1/gold-rates", rates);
app.route("/api/v1/suppliers", suppliers);
app.route("/api/v1/customers", customers);
app.route("/api/v1/products", products);
app.route("/api/v1/inventory", inventory);
app.route("/api/v1/accounts", accounts);
app.route("/api/v1/purchases", purchases);

export default app;
