import { Hono } from "hono";
import type { Env } from "./db/client";
import { errorHandler } from "./middleware/error";
import { cors } from "./middleware/cors";
import { accounts } from "./routes/accounts";
import { audit } from "./routes/audit";
import { auth } from "./routes/auth";
import { branches } from "./routes/branches";
import { bankAccounts, cash, settlements } from "./routes/cashbank";
import { catalog } from "./routes/catalog";
import { dayClosings } from "./routes/dayclose";
import { gold } from "./routes/gold";
import { expenseCategories, expenses } from "./routes/expenses";
import { health } from "./routes/health";
import { manufacturing } from "./routes/manufacturing";
import { melting } from "./routes/melting";
import { monthly } from "./routes/monthly";
import { counts } from "./routes/counts";
import { stockTransferRoutes } from "./routes/transfers";
import { discrepancies } from "./routes/discrepancies";
import { overview } from "./routes/overview";
import { repairRoutes } from "./routes/repairs";
import { customOrderRoutes } from "./routes/customOrders";
import { customers, suppliers } from "./routes/parties";
import { inventory } from "./routes/inventory";
import { oldgold } from "./routes/oldgold";
import { products } from "./routes/products";
import { purchases } from "./routes/purchases";
import { sales } from "./routes/sales";
import { rates } from "./routes/rates";
import { roles } from "./routes/roles";
import { settings } from "./routes/settings";
import { users } from "./routes/users";

const app = new Hono<{ Bindings: Env }>();
app.onError(errorHandler);
app.use("/api/*", cors);
app.route("/api/v1/health", health);
app.route("/api/v1/auth", auth);
app.route("/api/v1/users", users);
app.route("/api/v1/roles", roles);
app.route("/api/v1/branches", branches);
app.route("/api/v1/settings", settings);
app.route("/api/v1/audit", audit);
app.route("/api/v1/masters", catalog);
app.route("/api/v1/gold-rates", rates);
app.route("/api/v1/suppliers", suppliers);
app.route("/api/v1/customers", customers);
app.route("/api/v1/products", products);
app.route("/api/v1/inventory", inventory);
app.route("/api/v1/manufacturing", manufacturing);
app.route("/api/v1/gold", gold);
app.route("/api/v1/melting", melting);
app.route("/api/v1/oldgold", oldgold);
app.route("/api/v1/accounts", accounts);
app.route("/api/v1/expense-categories", expenseCategories);
app.route("/api/v1/expenses", expenses);
app.route("/api/v1/day-closings", dayClosings);
app.route("/api/v1/bank-accounts", bankAccounts);
app.route("/api/v1/cash", cash);
app.route("/api/v1/card-settlements", settlements);
app.route("/api/v1/purchases", purchases);
app.route("/api/v1/sales", sales);
app.route("/api/v1/reports", monthly);
app.route("/api/v1/counts", counts);
app.route("/api/v1/transfers", stockTransferRoutes);
app.route("/api/v1/discrepancies", discrepancies);
app.route("/api/v1/branch-overview", overview);
app.route("/api/v1/repairs", repairRoutes);
app.route("/api/v1/custom-orders", customOrderRoutes);

export default app;
