name = "goldos-api"
main = "src/app.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]

[vars]
WEB_ORIGIN = "http://localhost:3000"

[[d1_databases]]
binding = "DB"
database_name = "goldos"
database_id = "27c637f8-6a15-4012-bd7e-8b7b601df400"

[[r2_buckets]]
binding = "R2"
bucket_name = "goldos-assets"
